//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElGatoMensajero.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class conduce
    {
        [Required(ErrorMessage = "La matricula es obligatoria")]
        [StringLength(8, ErrorMessage = "Debe contener entre 6 y 8 caracteres", MinimumLength = 6)]
        public string matricula { get; set; }

        [Required(ErrorMessage = "El empleado es obligatorio")]
        public int empleado { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime fecha { get; set; }

        public virtual empleados empleados { get; set; }
        public virtual transportes transportes { get; set; }
    }
}
