//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElGatoMensajero.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elGatoMensajeroEntities : DbContext
    {
        public elGatoMensajeroEntities()
            : base("name=elGatoMensajeroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<conduce> conduce { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<estado_paquetes> estado_paquetes { get; set; }
        public virtual DbSet<paquetes> paquetes { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sedes> sedes { get; set; }
        public virtual DbSet<tipo_empleados> tipo_empleados { get; set; }
        public virtual DbSet<transportes> transportes { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
