//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElGatoMensajero.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleados()
        {
            this.conduce = new HashSet<conduce>();
            this.paquetes = new HashSet<paquetes>();
        }

        public int id { get; set; }

        [Required(ErrorMessage = "El DNI es obligatorio")]
        public string dni { get; set; }

        [Required(ErrorMessage = "El Nº de la Seguridad Social es obligatorio")]
        public string nss { get; set; }

        [Required(ErrorMessage = "La fecha de inicio de contrato es obligatoria")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime fecha_inicio { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> fecha_fin { get; set; }

        public Nullable<int> tipo { get; set; }

        public Nullable<int> sede { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conduce> conduce { get; set; }
        public virtual personas personas { get; set; }
        public virtual sedes sedes { get; set; }
        public virtual tipo_empleados tipo_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paquetes> paquetes { get; set; }
    }
}

