//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElGatoMensajero.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class paquetes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paquetes()
        {
            this.empleados = new HashSet<empleados>();
            this.sedes = new HashSet<sedes>();
        }

        public int id { get; set; }

        [Required(ErrorMessage = "El peso del paquete es obligatorio")]
        public double peso { get; set; }

        [Required(ErrorMessage = "Las dimensiones del paquete son obligatorias")]
        public string dimensiones { get; set; }

        public string estado { get; set; }

        public Nullable<int> emisor { get; set; }

        public Nullable<int> receptor { get; set; }

        [Required(ErrorMessage = "El remitente es obligatorio")]
        [StringLength(255, ErrorMessage = "Debe tener entre 2 y 255 carácteres", MinimumLength = 2)]
        public string nombreOrigen { get; set; }

        [Required(ErrorMessage = "El receptor es obligatorio")]
        [StringLength(255, ErrorMessage = "Debe tener entre 2 y 255 carácteres", MinimumLength = 2)]
        public string nombreDestino { get; set; }

        [Required(ErrorMessage = "La dirección del remitente es obligatoria")]
        [StringLength(255, ErrorMessage = "Debe tener entre 5 y 255 carácteres", MinimumLength = 5)]
        public string direccionOrigen { get; set; }

        [Required(ErrorMessage = "El código postal del remitente es obligatorio")]
        public Nullable<int> codPostalOrigen { get; set; }

        [Required(ErrorMessage = "El teléfono del receptor es obligatorio")]
        [DataType(DataType.PhoneNumber)]
        public Nullable<int> tlDestino { get; set; }

        [Required(ErrorMessage = "La dirección del receptor es obligatoria")]
        [StringLength(255, ErrorMessage = "Debe tener entre 5 y 255 carácteres", MinimumLength = 5)]
        public string direccionDestino { get; set; }

        [Required(ErrorMessage = "El código postal del receptor es obligatorio")]
        public Nullable<int> codPostalDestino { get; set; }

        [Required(ErrorMessage = "El teléfono del remitente es obligatorio")]
        [DataType(DataType.PhoneNumber)]
        public Nullable<int> tlOrigen { get; set; }

        public Nullable<double> longitud { get; set; }

        public Nullable<double> latitud { get; set; }

        public virtual estado_paquetes estado_paquetes { get; set; }
        public virtual personas personas { get; set; }
        public virtual personas personas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleados> empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sedes> sedes { get; set; }
    }
}
