//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElGatoMensajero.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sedes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sedes()
        {
            this.empleados = new HashSet<empleados>();
            this.transportes = new HashSet<transportes>();
            this.paquetes = new HashSet<paquetes>();
        }

        public int id { get; set; }

        [Required(ErrorMessage = "La provincia es obligatoria")]
        public string provincia { get; set; }

        [Required(ErrorMessage = "La localidad es obligatoria")]
        public string localidad { get; set; }

        [Required(ErrorMessage = "El código postal es obligatorio")]
        public int cp { get; set; }

        [Required(ErrorMessage = "La calle es obligatoria")]
        public string calle { get; set; }

        public Nullable<int> num { get; set; }

        [DataType(DataType.PhoneNumber)]
        public Nullable<int> telefono { get; set; }

        public Nullable<double> longitud { get; set; }

        public Nullable<double> latitud { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleados> empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transportes> transportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paquetes> paquetes { get; set; }
    }
}